plugins {
    id 'java'
    id 'antlr'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    antlr 'org.antlr:antlr4:4.13.2'
    implementation 'org.antlr:antlr4-runtime:4.13.2'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

generateGrammarSource {
    arguments += ['-visitor', '-no-listener']
    outputDirectory = file("src/main/java/gen")
}

test {
    useJUnitPlatform()
}